[build]
  base = "Rehabilitace"
  command = "npm rebuild lightningcss --update-binary || true && npm run build"
  publish = "Rehabilitace/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
